# Generated by Django 4.1.7 on 2023-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В процессе'), ('completed', 'Завершено')], default='new', max_length=12, verbose_name='Статус')),
                ('date_of_completion', models.DateField(blank=True, default=None, null=True, verbose_name='Дата завершения')),
            ],
        ),
    ]
